# SPDX-License-Identifier: GPL-2.0
# Copyright Amazon.com Inc. or its affiliates.

TEST_GEN_PROGS := bgp

CFLAGS =  -Wall -Wl,--no-as-needed -O2 -g
CFLAGS += -I../../../../include/uapi/

include ../../lib.mk
